apiVersion: v1
kind: Secret
metadata:
  name: db-secret-sql
  namespace: "{{ .Values.namespace }}"
type: Opaque
stringData:  
  db.server.name: "{{ .Values.db.ServerName }}"
  db.port.number: "{{ .Values.db.PortNumber }}"
  db.name: "{{ .Values.db.Name }}"
  db.user: "{{ .Values.db.User }}"
  db.password: "{{ .Values.db.Password }}"